dist: trusty
sudo: true
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petclinic;'
  - chmod +x mvnw
  - $HOME/.m2  
mvn test -Dspring.profiles.active=mysql-travis | grep "BUILD SUCCESS"
